#!/usr/bin/env node
/**
 * One codebase, one settings file per event.
 *
 *   events/<slug>.env   public settings for one race (name, date, colours,
 *                       logo, Supabase URL + publishable key). Committed.
 *
 * Pick the event with EVENT=<slug>, for example
 *
 *   EVENT=zagreb-2026 npm run build
 *   EVENT=zagreb-2026 npm run export:static
 *
 * Values already in the environment win, so a Cloudflare build variable or an
 * `export` in your shell still overrides the file. Secrets (the Supabase
 * service key, SESSION_SECRET, TURNSTILE_SECRET) never go in these files.
 *
 * As a script (it runs before every `next build`) it writes the chosen event
 * to .env.production.local, which Next.js reads during the build. Without
 * EVENT it removes a file it wrote earlier, so an old event can't leak into
 * the next build.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';

const WEB = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const GENERATED = path.join(WEB, '.env.production.local');
const MARK = '# generated by scripts/event-env.mjs';

export function eventFile(slug) {
  return path.join(WEB, 'events', `${slug}.env`);
}

/** Load events/<EVENT>.env into process.env without overriding what is set. */
export function loadEvent(slug = process.env.EVENT) {
  if (!slug) return null;
  const file = eventFile(slug);
  if (!fs.existsSync(file)) {
    const known = fs.existsSync(path.join(WEB, 'events'))
      ? fs.readdirSync(path.join(WEB, 'events')).filter((f) => f.endsWith('.env')).map((f) => f.slice(0, -4))
      : [];
    throw new Error(`EVENT=${slug}: no file events/${slug}.env (known: ${known.join(', ') || 'none'})`);
  }
  const values = dotenv.parse(fs.readFileSync(file));
  for (const [k, v] of Object.entries(values)) {
    if (process.env[k] === undefined) process.env[k] = v;
  }
  return values;
}

// Run directly: write (or clear) .env.production.local for `next build`.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const slug = process.env.EVENT;
  if (!slug) {
    if (fs.existsSync(GENERATED) && fs.readFileSync(GENERATED, 'utf8').startsWith(MARK)) {
      fs.unlinkSync(GENERATED);
      console.log('[event] no EVENT set: removed the previous event settings');
    }
    process.exit(0);
  }
  try {
    const values = loadEvent(slug);
    const lines = Object.entries(values).map(([k, v]) => `${k}=${JSON.stringify(v)}`);
    fs.writeFileSync(GENERATED, `${MARK} for EVENT=${slug}\n${lines.join('\n')}\n`);
    console.log(`[event] building ${slug} (${Object.keys(values).length} settings from events/${slug}.env)`);
  } catch (e) {
    console.error(`[event] ${e.message}`);
    process.exit(1);
  }
}
